log_level: 20
main_fps: 60
mp_cfg:
  enable_segmentation: true
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5
  model_complexity: 1
  smooth_landmarks: true
  smooth_segmentation: true
  static_image_mode: false
no_local_test: false
worker_cfg:
  cv2_args:
    - 1
  cv2_height: 720
  cv2_width: 1280
  max_fps: 30
  wss_host: localhost
  wss_port: 1234
