version: '3.9'
services:
  nicepipe:
    build: .
    ports:
      - '8000:8000/tcp'
      - '8000:8000/udp'
    devices:
      - '/dev/video0:/dev/video0'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  coturn:
    image: coturn/coturn:alpine
    network_mode: host
