[tool.poetry]
name = "mediapiping"
version = "0.1.0"
description = "insert description"
license = "Proprietary"
authors = ["John-Henry Lim <42513874+Interpause@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "^1.22.3"
opencv-contrib-python = "^4.5.5"
websockets = "^10.2"
protobuf = "^3.20.0"
mediapipe = "^0.8.9.1"
aioprocessing = "^2.0.0"
uvloop = {version = "^0.16.0", platform = "linux"}
rich = "^12.2.0"

[tool.poe.tasks]
## PyTorch with CUDA 11.1. If PyTorch is imported first, importing Tensorflow will detect CUDA + cuDNN bundled with PyTorch
## Run with the command "poe post-update"
## See https://github.com/python-poetry/poetry/issues/2543
post-update = "pip install torch==1.11.0+cu115 torchvision==0.12.0+cu115 -f https://download.pytorch.org/whl/torch_stable.html"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.13.1"
autopep8 = "^1.6.0"
line-profiler = "^3.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
